[package]
name = "czwordle"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
rand = "0.8.4"
clap = { version = "3.0.13", features = ["derive"] }
macroquad = "0.3"